### ISSUE TITLE
Create a Calendar page

### ISSUE THREAD

**Issue by leahyanagisawa** [happeningatmanoa/happeningatmanoa#9]

**Comment by leahyanagisawa** [comment]
Please do work for this task in a branch called issue-08.

Implement a calendar page with a full month calendar including all events posted on application, including non subscribed clubs/events.
Perhaps highlighting today (as the ICS schedule is) and have calendar auto update for month changes.

**thinking about if we should add a scraper from UH calendar events or if having the events posted by clubs is enough.

**Comment by anthonywonjoon** [comment]
Completed the basic grid for the Calendar
